name: CI/CD for Iris Model

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/iris-model-app .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/iris-model-app

    - name: Deploy to EC2 and run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "== Checking for containers on port 8000 =="
          docker ps -a

          echo "== Stopping/removing containers using port 8000 =="
          docker rm -f $(docker ps -q --filter "publish=8000") || true

          echo "== Pulling latest image =="
          docker pull ${{ secrets.DOCKER_USERNAME }}/iris-model-app

          echo "== Running new container =="
          docker run -d -p 8000:8000 --name iris-app ${{ secrets.DOCKER_USERNAME }}/iris-model-app

          echo "== Verifying deployment =="
          curl -s http://localhost:8000/

